name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          script: whoami
        
      - name: Build application
        run: |
          go build -o icapeg
          
      - name: Copy files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          source: icapeg
          target: /usr/local/go/src/icapeg
          
      - name: Start updated application
        run: |
          sudo systemctl start icapeg
          
      - name: Stop current application
        run: |
          sudo systemctl stop icapeg
          

      - name: Restart application
        run: |
          ssh -tt linux@23.106.36.101 -p 22234
          sudo systemctl restart icapeg
