name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          script: |
            export PATH=$PATH:/usr/local/go/bin
            go version 
            rm -r icapeg
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: egirna/icapeg
          ref: main
          path: /home/linux/icapeg 
