name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: executing remote ssh commands using password
        timeout-minutes: 1
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            export PATH=$PATH:/usr/local/go/bin
            go version 
            rm -r icapeg
            tmux kill-session -t icapeg
            tmux new-session -s icapeg -d
            git clone "https://github.com/egirna/icapeg"
            cd /home/mahmoud/icapeg
            rm config.toml && cp /home/mahmoud/config.toml
            git checkout develop
            git branch
           
          
            
