name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy code
      run: |
        ssh linux@23.106.36.101 -p 22234 "cd /home/linux/icapeg && git pull"
        ssh linux@23.106.36.101 -p 22234 "cd /home/linux/icapeg && ./deploy.sh"
